ALTER TABLE departments ADD COLUMN description VARCHAR(500);
ALTER TABLE departments ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE departments ADD COLUMN updated_at TIMESTAMP;
ALTER TABLE departments ADD COLUMN deleted_at TIMESTAMP;

ALTER TABLE users ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE users ADD COLUMN updated_at TIMESTAMP;
ALTER TABLE users ADD COLUMN deleted_at TIMESTAMP;
